project:
  type: website
  output-dir: _site

website:
  title: "SURGE NeuroTech Club"
  google-analytics: 
    tracking-id: G-KW75ZEEZEM
    anonymize-ip: true
  cookie-consent:
    type: implied
    palette: dark
  image: images/logo.png
  favicon: images/logos/logo_favicon_transparent.png
  # favicon: images/logos/new_favicon.webp
  bread-crumbs: true
  page-navigation: true
  open-graph: true
  search: 
    show-item-context: true
    location: navbar
    type: overlay

  navbar:
    logo: images/logos/logo_transparent.png
    collapse-below: lg
    right:
      - icon: github
        href: https://github.com/orgs/SURGE-NeuroTech-Club
        target: _blank
    left:
      - text: "Tutorials"
        href: docs/tutorials/index.qmd
      # - text: "Get Started"
      #   menu:
      #     - docs/get-started/getting_setup.qmd
      # - text: Resources
      #   href: resources.qmd
      - text: "Who We Are"
        href: who_we_are.qmd
      - text: "GitHub"
        icon: github
        href: https://github.com/orgs/SURGE-NeuroTech-Club/repositories
        target: _blank

  # sidebar:
  #   style: floating
  #   search: true
  #   contents: auto

  page-footer:
    background: dark 
    left: 
      - text: "Copyright 2024, SURGE Innovation" 
    center:
      - text: "About Site"
        href: site_info.qmd
      - text: "Contact Us"
        href: contact_us.qmd
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/SURGE-NeuroTech-Club/SURGE-NeuroTech-Club.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}


format:
  html:
    toc: true
    # theme: darkly #[darkly, theme.scss]
    # theme: styles.scss
    theme: [darkly, styles.scss]
    # mainfont: *insert font*
    appearance: false 
    code-copy: true
    code-overflow: wrap
    css: styles.scss
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px



