name: Build Quarto Preview

on:
  pull_request:
    branches:
      - main

env:
  PREVIEWS_FOLDER: preview

permissions:
    contents: write
    pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # for debugging
      - name: Print Contexts
        uses: crazy-max/ghaction-dump-context@v1

      - name: Checkout Branch Contents
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Get Latest Pre-release from Github
        if: github.event.action != 'closed'
        id: github-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo version=$(gh api repos/quarto-dev/quarto-cli/releases | jq -r 'map(select(.prerelease)) | first | .tag_name | sub("^v";"")') >> "$GITHUB_OUTPUT"    

      - name: Set up Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify Python 3.12

      - name: Install Jupyter and Python dependencies
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat  # Install Jupyter and nbformat
          pip install -r requirements.txt  # Install other dependencies

      - name: Set up Quarto
        if: github.event.action != 'closed'
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ steps.github-release.outputs.version }}

      - name: Build Preview
        if: github.event.action != 'closed'
        run: quarto render --output-dir="${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.number }}"
        
      - name: Commit Preview to Pages Branch
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          umbrella-dir: ${{ env.PREVIEWS_FOLDER }}"
